### ISSUE TITLE
Interservice calls and message context

### ISSUE THREAD

**Issue by smoliji** [AckeeCZ/crudella#16]
What is the correct way to call another service method within a same context?

```ts
const thisService = createService<Attributes>({
    // [...]
    create: async ctx => {
        // do important services stuff
        // and finally, call another service
        anotherService.create({ ...ctx, data: { /* ... */ } })
    }
```

From `thisService` I call `anotherService` with the _same_ context - because initial message is the same, user is the same etc, just internal parameters change.

Currently this is not possible due to an type error
```
Argument of type '{ data: {}; bareData: any; write: true; safe: false; 
context: IContextInterface; options: any; 
entity?: Attributes | undefined; }'
is not assignable to parameter of type 'CreateContext<AnotherAttributes, any>'
Types of property 'entity' are incompatible.
```

I think it makes sense to do a few service call on behalf of the initial call, but for that there should be possible to modify the context.

I presented a create operation, but this makes sense also with other methods.

**Comment by smolijar** [comment]
This problem should be probably solved via refactoring the exposed behavior to sperate function. Crudella aims to solve the 80% of the cases, it's not an all powered tool you should use for every part of your codebase.

```typescript
const createAnother = (data: any) => {
  // ...
}
const anotherService = createService<AnotherAttributes>({
    // [...]
    create: async ctx => {
        return createAnother(ctx.data)
    }
});

const thisService = createService<Attributes>({
    // [...]
    create: async ctx => {
        // do important services stuff
        // and finally, call another service
        createAnother(ctx.data)
    }
```

If you come up with a reasonable solution, present it or feel free to publish a PR.

**Comment by smolijar** [comment]
Feel free to reopen, if you still have interest in the issue
